language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

branches:
  only:
    - master

script:
  - npm install

cache:
  directories:
  - node_modules

notifications:
  email:
    - latchkey@gmail.com
